### ISSUE TITLE
berkshelf-api breaks with ruby 2.x.x include in chefdk

### ISSUE THREAD

**Issue by AnalogJ** [berkshelf/berkshelf-api#163]
We're getting the following error when installing berkshelf-api via chefdk (v0.2.1-1)

	==> preview: [2014-09-11T20:51:13+00:00] INFO: github_asset[berkshelf-api.tar.gz] downloading asset
	==> preview: [2014-09-11T20:51:13+00:00] INFO: libarchive_file[berkshelf-api.tar.gz] extracting /var/chef/cache/github_assets/berkshelf/berkshelf-api/v2.1.0/berkshelf-api.tar.gz to /opt/berkshelf-api/v2.1.0
	==> preview:
	==> preview: ================================================================================
	==> preview: Error executing action `extract` on resource 'libarchive_file[berkshelf-api.tar.gz]'
	==> preview: ================================================================================
	==> preview:
	==> preview:
	==> preview: NameError
	==> preview: ---------
	==> preview: uninitialized constant Archive::EXTRACT_OWNER
	==> preview:
	==> preview:
	==> preview: Cookbook Trace:
	==> preview: ---------------
	==> preview: /tmp/vagrant-chef-2/cookbooks/cookbooks/libarchive/libraries/helper.rb:14:in `extract_option_map'
	==> preview:
	==> preview: /tmp/vagrant-chef-2/cookbooks/cookbooks/libarchive/libraries/helper.rb:34:in `block in extract'
	==> preview:
	==> preview: /tmp/vagrant-chef-2/cookbooks/cookbooks/libarchive/libraries/helper.rb:34:in `collect!'
	==> preview:
	==> preview: /tmp/vagrant-chef-2/cookbooks/cookbooks/libarchive/libraries/helper.rb:34:in `extract'
	==> preview:
	==> preview: /tmp/vagrant-chef-2/cookbooks/cookbooks/libarchive/providers/file.rb:18:in `block in class_from_file'
	==> preview:
	==> preview:
	==> preview: Resource Declaration:
	==> preview: ---------------------
	==> preview: # In /tmp/vagrant-chef-2/cookbooks/cookbooks/berkshelf-api-server/recipes/app.rb
	==> preview:
	==> preview:  47: libarchive_file "berkshelf-api.tar.gz" do
	==> preview:  48:   path asset.asset_path
	==> preview:  49:   extract_to node[:berkshelf_api][:deploy_path]
	==> preview:  50:   extract_options :no_overwrite
	==> preview:  51:   owner node[:berkshelf_api][:owner]
	==> preview:  52:   group node[:berkshelf_api][:group]
	==> preview:  53:
	==> preview:  54:   action :extract
	==> preview:  55:   notifies :restart, "runit_service[berks-api]"
	==> preview:  56:   only_if { ::File.exist?(asset.asset_path) }
	==> preview:  57: end
	==> preview:  58:
	==> preview:
	==> preview: Compiled Resource:
	==> preview: ------------------
	==> preview: # Declared in /tmp/vagrant-chef-2/cookbooks/cookbooks/berkshelf-api-server/recipes/app.rb:47:in `from_file'
	==> preview:
	==> preview: libarchive_file("berkshelf-api.tar.gz") do
	==> preview:   action [:extract]
	==> preview:   retries 0
	==> preview:   retry_delay 2
	==> preview:   guard_interpreter :default
	==> preview:   cookbook_name :"berkshelf-api-server"
	==> preview:   recipe_name "app"
	==> preview:   path "/var/chef/cache/github_assets/berkshelf/berkshelf-api/v2.1.0/berkshelf-api.tar.gz"
	==> preview:   extract_to "/opt/berkshelf-api/v2.1.0"
	==> preview:   extract_options :no_overwrite
	==> preview:   owner "berkshelf"
	==> preview:   group "berkshelf"
	==> preview:   mode 493
	==> preview:   only_if { #code block }
	==> preview: end
	==> preview:
	==> preview: [2014-09-11T20:51:13+00:00] INFO: Running queued delayed notifications before re-raising exception
	==> preview: [2014-09-11T20:51:13+00:00] ERROR: Running exception handlers
	==> preview: [2014-09-11T20:51:13+00:00] ERROR: Exception handlers complete
	==> preview: [2014-09-11T20:51:13+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
	==> preview: [2014-09-11T20:51:13+00:00] ERROR: libarchive_file[berkshelf-api.tar.gz] (berkshelf-api-server::app line 47) had an error: NameError: uninitialized constant Archive::EXTRACT_OWNER
	==> preview: [2014-09-11T20:51:13+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
	Chef never successfully completed! Any errors should be visible in the
	output above. Please fix your recipes so that they properly complete.

The interesting thing is that everything works correctly when we install via chef-solo (http://www.getchef.com/download-chef-client/) And we determined that the chef solo installer uses an older version of ruby that libarchive works with.

**Comment by lamont-granquist** [comment]
#218 should address libarchive tickets
