### ISSUE TITLE
Github worker uses repository name vs cookbook name

### ISSUE THREAD

**Issue by berniedurfee** [berkshelf/berkshelf-api#164]
Is this by design or by accident?

In github.rb...
```
...
if cookbook_metadata.version.to_s == match[:version].to_s
  cookbook_versions << RemoteCookbook.new(repo.name, cookbook_metadata.version,
  self.class.worker_type, repo.html_url, priority)
else
...
```

Shouldn't the RemoteCookbook name be set to the cookbook_metadata.name?

**Comment by reset** [comment]
Fixed by #166

**Comment by MurgaNikolay** [comment]
Hello.
If github repo name is not equal cookbook's name in metadata.rb, method load_metadata cannot loads metadata from repository.

https://github.com/berkshelf/berkshelf-api/blob/36f15ff8324d9267e94100412685540958583aea/lib/berkshelf/api/cache_builder/worker/github.rb#L79

**Comment by MurgaNikolay** [comment]
Already fixed by @gueux https://github.com/berkshelf/berkshelf-api/pull/179
