### ISSUE TITLE
libarchive dependency 

### ISSUE THREAD

**Issue by GenaSG** [berkshelf/berkshelf-api#167]
Hello.
I've installed berks-api from gem repo as per installation instruction. 
But it looks like that instruction is missing libarchive dependency related info.
Gem installations also finished successfully without libarchive dependancy installation. But because of missing dependency it failed to start.
Please update installation documentation and/or gem with libarchive dependency.
Thank you in advance.

**Comment by toddiuszho** [comment]
For RHEL6, I had to install libarchive package and create a symlink to satisfy libarchive.so dependency.

**Comment by CVTJNII** [comment]
Installing libarchive-dev on Ubuntu 14.04 resolved this for me.

**Comment by mnovacyu** [comment]
@toddiuszho can you specify the symlink you created to resolve this issue?  Thanks!

**Comment by lamont-granquist** [comment]
#218 should address libarchive tickets
