### ISSUE TITLE
Empty cerch file after Failed to get `https://supermarket.getchef.com/universe.json' in 15 seconds!

### ISSUE THREAD

**Issue by mwalton236** [berkshelf/berkshelf-api#170]
Every now and then an error Failed to get `https://supermarket.getchef.com/universe.json' in 15 seconds! occurs. After this point the cerch file is saved empty, leading to Berkshelf::API::InvalidSaveError: A JSON text must at least contain two octets!

Using berkshelf-api 2.1.0

E, [2014-12-11T09:45:09.863788 #23193] ERROR -- : Failed to get `https://supermarket.getchef.com/universe.json' in 15 seconds!
E, [2014-12-11T09:45:09.864538 #23193] ERROR -- : Actor crashed!
NoMethodError: undefined method `inject' for true:TrueClass
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/cache_builder/worker/supermarket.rb:17:in `cookbooks'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
E, [2014-12-11T09:45:09.879379 #23193] ERROR -- : Actor crashed!
NoMethodError: undefined method `inject' for true:TrueClass
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/cache_builder/worker/supermarket.rb:17:in `cookbooks'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    (celluloid):0:in `remote procedure call'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/cache_manager.rb:83:in `process_worker'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
I, [2014-12-11T09:45:09.887428 #23193]  INFO -- : Cache Manager shutting down...
I, [2014-12-11T09:45:09.887717 #23193]  INFO -- : Saving the cache to: /home/berkshelf/.berkshelf/api-server/cerch
I, [2014-12-11T09:45:10.282265 #23193]  INFO -- : Cache saved!
W, [2014-12-11T09:45:10.284246 #23193]  WARN -- : Terminating task: type=:call, meta={:method_name=>:process_workers}, status=:receiving
    Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
I, [2014-12-11T09:45:10.286909 #23193]  INFO -- : Cache manager starting...
I, [2014-12-11T09:45:10.287974 #23193]  INFO -- : Loading save from /home/berkshelf/.berkshelf/api-server/cerch
I, [2014-12-11T09:45:10.591011 #23193]  INFO -- : Cache contains 9255 items
I, [2014-12-11T09:45:15.592351 #23193]  INFO -- : Processing chef_server: https://chef.laterooms.com
I, [2014-12-11T09:45:16.566959 #23193]  INFO -- : Found 1189 cookbooks from chef_server: https://chef.laterooms.com
I, [2014-12-11T09:45:16.615459 #23193]  INFO -- : About to merge cookbooks
I, [2014-12-11T09:45:16.615615 #23193]  INFO -- : Cache manager adding (0) items...
I, [2014-12-11T09:45:16.615681 #23193]  INFO -- : Cache manager removing (0) items...
I, [2014-12-11T09:45:16.615745 #23193]  INFO -- : Cache manager cache updated.
I, [2014-12-11T09:45:16.615827 #23193]  INFO -- : Cache manager cache updated.
I, [2014-12-11T09:45:16.616039 #23193]  INFO -- : Processing supermarket
E, [2014-12-11T09:45:31.654607 #23193] ERROR -- : Failed to get `https://supermarket.getchef.com/universe.json' in 15 seconds!
E, [2014-12-11T09:45:31.655148 #23193] ERROR -- : Actor crashed!
NoMethodError: undefined method `inject' for true:TrueClass
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/cache_builder/worker/supermarket.rb:17:in `cookbooks'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
I, [2014-12-11T09:45:36.702994 #23193]  INFO -- : Processing chef_server: https://chef.laterooms.com
I, [2014-12-11T09:45:36.704243 #23193]  INFO -- : Processing supermarket
I, [2014-12-11T09:45:37.569148 #23193]  INFO -- : Found 1189 cookbooks from chef_server: https://chef.laterooms.com
I, [2014-12-11T09:45:37.617748 #23193]  INFO -- : About to merge cookbooks
I, [2014-12-11T09:45:37.618121 #23193]  INFO -- : Cache manager adding (0) items...
I, [2014-12-11T09:45:37.618344 #23193]  INFO -- : Cache manager removing (0) items...
I, [2014-12-11T09:45:37.618560 #23193]  INFO -- : Cache manager cache updated.
I, [2014-12-11T09:45:37.618838 #23193]  INFO -- : Saving the cache to: /home/berkshelf/.berkshelf/api-server/cerch
I, [2014-12-11T09:45:41.642990 #24514]  INFO -- : Cache manager starting...
I, [2014-12-11T09:45:41.643228 #24514]  INFO -- : Loading save from /home/berkshelf/.berkshelf/api-server/cerch
E, [2014-12-11T09:45:41.643408 #24514] ERROR -- : Actor crashed!
Berkshelf::API::InvalidSaveError: A JSON text must at least contain two octets!
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/dependency_cache.rb:32:in `rescue in from_file'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/dependency_cache.rb:27:in `from_file'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/cache_manager.rb:123:in `load_save'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-api-2.1.0/lib/berkshelf/api/cache_manager.rb:28:in `initialize'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
I, [2014-12-11T09:45:41.652732 #24514]  INFO -- : Cache Manager shutting down...
E, [2014-12-11T09:45:41.643504 #24514] ERROR -- : Actor crashed!

**Comment by reset** [comment]
Fixed by https://github.com/berkshelf/berkshelf-api/pull/174
