### ISSUE TITLE
blacklist

### ISSUE THREAD

**Issue by koertkuipers** [berkshelf/berkshelf-api#173]
i realize berkshelf works with a flat namespace, and its my responsibility to name internal cookbooks so that they do not conflict with the ones in the public supermarket.

but every once in a while we all mess up. so we have an internal cookbook that didnt have unique enough of a name, and suddenly the same name is also in the public supermarket. i am sure i have no intention of using the one in the public supermarket, and i am sure it will never want it to be a transitive dependency either. renaming an internal cookbook in production is not really an option. so i just want it to go away on the public supermarket. a simple blacklist per source would do this for me. would you consider this?

thanks koert

**Comment by sethvargo** [comment]
Hi @koertkuipers,

Berkshelf searches sources in the order they are specified in the Berksfile. If you specify your internal cookbook API server location FIRST in the Berksfile (before supermarket.chef.io), that location will be preferred. If you're experiencing other behavior, that is definitely a bug we should investigate. Are you running an internal Berkshelf API server?

**Comment by koertkuipers** [comment]
Hey Seth,
Thanks for responding. Yes i am running an internal Berkshelf API server.

My understanding was that the preference with respect to order of the
sources only helps to break ties for the same version. But that does not
help me if i have an inhouse cookbook "x" version 0.9 and suddenly someone
drops an unrelated cookbook "x" version 1.2 on the public supermarket.

I guess it would help if i pin the version, that is a fair point.


Best, Koert

**Comment by sethvargo** [comment]
Nope. It prefers them on name. Given:

```ruby
source "api1.server"
source "api2.server"

cookbook "foo"
```
Even if api2 has a cookbook foo, it should prefer the one from api1. If you specify a version, it will prefer the one that best matches the constraint.

**Comment by koertkuipers** [comment]
Oh in that case i misunderstood the logic. I will definitely try that.
Thanks
