### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by dblessing** [berkshelf/berkshelf-api#175]
I just wanted to drop a note saying I find this extremely useful. There was a comment in another issue suggesting the internal Supermarket was the way to go now. The Supermarket is great but for us is way too much. Berkshelf API is perfectly simple. I hope you'll keep developing this project going forward. Of course, if we encounter issues we will do our best to contribute fixes. Thanks for your work!

**Comment by reset** [comment]
@dblessing thanks for the kind comments. This project will be supported until there is a solution built into the Chef Server itself. The Supermarket is *not* the appropriate solution for an internal index of your cookbooks.

**Comment by dblessing** [comment]
Glad to hear it!
