### ISSUE TITLE
berkshelf-api-server cookbook does not work with latest libarchive 0.5 on Chef 11

### ISSUE THREAD

**Issue by svacko** [berkshelf/berkshelf-api#187]
berkshelf-api-server has dependency on libarchive ~> 0.4. Latest libarchive 0.5.0 satisfying this dependency requires Chef ~> 12.1 (https://supermarket.chef.io/cookbooks/libarchive/versions/0.5.0), thus berkshelf-api-server cookbook deploy on the node with chef-client v11.x installed fails with following error: https://gist.github.com/svacko/137126a215c9774a6fde

I recommend to bind berkshelf-api-server cookbook to libarchive ~>0.4.0 instead of ~>0.4 so that it will depend on 0.4.x branch of libarchive cookbook and thus support Chef v11.x also.

**Comment by matt-altiscale** [comment]
I use a wrapper cookbook to install.  My berksfile for this forces the version of libarchive to 0.4.4.

**Comment by lamont-granquist** [comment]
not going to be supporting Chef 11 going forwards.
