### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by gueux** [berkshelf/berkshelf-api#191]
Hi, 
We have some unexpected memory leaks with berkshelf api

It allocates about 340MB exactly after starting:

ubuntu@chef ➜  htop
 PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
` 2830 ubuntu     20   0  956M  340M  5864 S 63.6  9.1  0:30.40 - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3174 ubuntu     20   0  956M  340M  5864 S  0.0  9.1  0:00.05 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3173 ubuntu     20   0  956M  340M  5864 S 13.1  9.1  0:04.67 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3172 ubuntu     20   0  956M  340M  5864 S  7.2  9.1  0:13.18 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3171 ubuntu     20   0  956M  340M  5864 S  0.0  9.1  0:00.00 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3170 ubuntu     20   0  956M  340M  5864 S  0.0  9.1  0:00.00 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3169 ubuntu     20   0  956M  340M  5864 R 42.0  9.1  0:10.18 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3168 ubuntu     20   0  956M  340M  5864 S  0.0  9.1  0:00.06 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
` 3161 ubuntu     20   0  956M  340M  5864 S  0.0  9.1  0:00.00 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`

but increases up to ~700MB after one day of usage and still grows up.

ubuntu@chef ➜  htop
 PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
`25218 ubuntu     20   0 1209M  674M  3060 S 13.2 17.9  8h36:06 - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25562 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9  0:06.44 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25561 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9 30:50.15 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25560 ubuntu     20   0 1209M  674M  3060 S 12.5 17.9  4h02:51 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25559 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9  0:01.29 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25558 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9  0:02.79 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25557 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9  4h01:09 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25556 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9  0:00.06 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`
`25550 ubuntu     20   0 1209M  674M  3060 S  0.0 17.9  0:08.09 |  - ruby bin/berks-api -p 26200 -c /etc/berkshelf/api-server/config.json`

While the size of cache file is unchanged:

`ubuntu@chef ➜  ~  ls -lah /home/ubuntu/.berkshelf/api-server/cerch`
`-rw-r--r-- 1 ubuntu ubuntu 2.5M Aug 13 10:43 /home/ubuntu/.berkshelf/api-server/cerch`

We are using ruby-2.2.1 with RVM, so should it be downgraded to recommened 2.0.0?

**Comment by tschroeder-zendesk** [comment]
I have too have seen some leaks. Our memory usage has been growing each day. We are using rbenv and ruby version 2.1.6

**Comment by lamont-granquist** [comment]
Would really need to see this replicated again on a more recent 2.1/2.2/2.3/2.4 series kernel.  I believe ruby's VM itself was fairly leaky (and may still be fairly leaky in the 2.1 series?).
