### ISSUE TITLE
testsuit hangs with rspec 3.3

### ISSUE THREAD

**Issue by 375gnu** [berkshelf/berkshelf-api#192]
Hi, when testsuit is run with rspec 3.3 it will hang on https://github.com/berkshelf/berkshelf-api/blob/master/spec/unit/berkshelf/api/cache_builder/worker/github_spec.rb#L51

There is a good explanation what's wrong from one of rspec authors: 
https://github.com/rspec/rspec-core/issues/2064#issuecomment-133009123

**Comment by lamont-granquist** [comment]
#214
