### ISSUE TITLE
error retrieving universe 

### ISSUE THREAD

**Issue by d4v3y0rk** [berkshelf/berkshelf-api#203]
```
Error retrieving universe from source: http://berkshelf-api.ourdomain.com
  * [Berkshelf::APIClient::ServiceUnavaiable] service unavailable at: http://berkshelf-api.ourdomain.com
```
restarting the service seems to have fixed this. 
we are running v2.1.0 or the api server

**Comment by d4v3y0rk** [comment]
found this in the logs
```
2016-01-04_21:51:57.03216 E, [2016-01-04T20:50:15.893055 #10729] ERROR -- : Actor crashed!
2016-01-04_21:51:57.03217 Berkshelf::API::NotStartedError: cache_manager not running
```
it looked like there were cache updated in the logs after this message so I am not sure if this is what was causing the issue or not.

**Comment by scalp42** [comment]
Same issue here, restarting it on a cron pretty much.

**Comment by lamont-granquist** [comment]
Not an actionable bug report would need a lot more details.
