### ISSUE TITLE
gem install berkshelf-api fails

### ISSUE THREAD

**Issue by arieb** [berkshelf/berkshelf-api#209]
On a fresh ubuntu server 14.04.3

```
test:~$ gem install berkshelf-api
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: berkshelf-api requires celluloid (~> 0.16); reel requires celluloid (>= 0.15.1); ridley requires celluloid (
~> 0.16.0); celluloid-io requires celluloid (>= 0.16.0)
```

ruby and gem versions:
```
test:~$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```
```
test:~$ gem -v
1.8.23
```

**Comment by someara** [comment]
Could it be that old version of gem is resolving the dep graph incorrectly?
The only thing I can think to do is add a dep on reel (~> 0.6.0)

**Comment by lamont-granquist** [comment]
rubygems 1.8.24 had the old bug with the json gem and fencing with 1.7.7

solving this basically by dropping support for anything that old.
